force-app/main/default/objects/Case_Callout__c/Case_Callout__c.object-meta.xml
<CustomObject>
    <label>Case Callout</label>
    <nameField>
        <displayFormat>CL-{YYMM}-{0000}</displayFormat>
        <label>Case Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Callouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Callout__c/fields/AgentId__c.field-meta.xml
<CustomField>
    <fullName>AgentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AgentId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Callouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Callout__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Callouts</relationshipLabel>
    <relationshipName>Case_Callouts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Callout__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <label>Response Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseCalloutJobs.cls
public class CaseCalloutJobs implements Queueable, Database.AllowsCallouts { 

    private List<Case> queueCases { get; set; }
    
    //Constructor, storing input list values for processing below
    public CaseCalloutJobs(List<Case> inputCases){
        this.queueCases = inputCases;
    }
    
    //Queueable Context execution.  Run through each 
    public void execute(QueueableContext context) {
        
        //expected input is a filtered list of cases, where status was updated to 'Closed'
        List<Case_Callout__c > caseCallouts = new List<Case_Callout__c >();


		//As Salesforce has a limit of 100 callouts per transaction, use counter to requeue (if needed)
		integer i = 0;
        
        //Check each case, to ensure status has changed and is currently 'Closed'
        for(Case newCase : queueCases){
          
            //increment counter
            i++;
            
            //create initial Case Callout for each case, and add it to the map
            caseCallouts.add(new Case_Callout__c(Case__c = newCase.Id,
                                                 AgentId__c = newCase.LastModifiedById,
                                                 Response_Status__c = 'Queued'));
            
        
    	}
    
        //http://enreeco.blogspot.com/2014/11/salesforce-apex-queueable-interfaces.html#tldr_async_queueable
        
        //create 
        if(!caseCallouts.isEmpty()){
            insert caseCallouts;
        }
    
	}
}